<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "user_customer"
 *
 * Auto generated by Extension Builder 2018-03-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'Customer template',
    'description'      => 'Customer template used with distribution pizpalue',
    'category'         => 'templates',
    'author'           => 'Roman Büchler',
    'author_email'     => 'rb@buechler.pro',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '8.0.2',
    'constraints'      => [
        'depends'   => [
            'typo3'             => '8.7.0-8.99.99',
            'bootstrap_package' => '8.0.0-8.99.99',
            'pizpalue'          => '8.2.3-8.99.99'
        ],
        'conflicts' => [
        ],
        'suggests'  => [
        ],
    ],
];
